### PR TITLE
fix suffixeadd

### PR DESCRIPTION
**Pull request by eiro**
* remove useless extensions (so i think ...)
* add .rakumode

### CODE REVIEW

**Comment by zostay** [comment]
I want to support all the extensions listed here, plus the legacy Perl 6 ones for now:

https://github.com/Raku/problem-solving/blob/master/solutions/language/Path-to-Raku.md#extensions

I'm fine with removing `.pm` and `.t6`. but at least `.raku`, `.rakumod`, `.rakudoc`, and `.rakutest` should be supported.

**Comment by eiro** [comment]
i don't understand why you want to add so many extensions in suffixadd. can you provide me the some exemples of usecases?

**Comment by zostay** [comment]
To clarify, my knowledge of vim settings is iffy, so when I see something like `suffixadd` with a bunch of suffixes, I think, "oh, that means I should add all the recommended suffixes there." I've just taken some time to read about what that setting is used for because your comments suggested I didn't know what I am talking. Please feel free to treat me like Michael Scott of The Office when explaining vim to me because I'm nothing like an expert, but I am learning.

I'm still not sure I understand all the ways in which `suffixadd` is used, but I am starting to see why having all the suffixes there might not be a good idea. On the other hand, I'm also thinking that leaving `.pm` as well as `.pm6` is reasonable because there are still modules using the `.pm` suffix.

Anyway, make an argument for doing whatever you think is best, and I will consider it. I do not want to be a tyrant and I don't even want to do most of the work on this. Just don't assume I know what I'm talking about. I don't.

**Comment by eiro** [comment]
> To clarify, my knowledge of vim settings is iffy, so when I see
> something like `suffixadd` with a bunch of suffixes, I think, "oh,
> that means I should add all the recommended suffixes there."

nope. as the documentation states:

        'suffixesadd' 'sua'
            Comma separated list of suffixes, which are used when searching for a
            file for the "gf", "[I", etc. commands.

so finding a place to a module to make gf work, you combine

    " path for possible dirnames
    let &l:path = "lib,.,".$RAKULIB.",".join(glob("~/.zef/store/*/*/lib",0,1),',')

    " inex to convert a namespace to a relative path from a dirnames
    setlocal includeexpr=substitute(v:fname,'::','/','g')

    " suffixesadd for the extensions
    setlocal suffixesadd=.pm6,.rakumod

> because your comments suggested I didn't know what I am talking.

after 25 years of happy viming, i still learn new useful things every year
so i asked for usecases because you may have one in mind that can
explain the other extensions.

> free to treat me like Michael Scott of The Office

i'm sorry, i don't know the Michael Scott :( from what office are you
talking about?

> to me because I'm nothing like an expert, but I am learning.

so do i but i'll share whatever can help

> Anyway, make an argument for doing whatever you think is best, and I
> will consider it.

i really think we should prevent any accidental behavior so we should
keep the code of the module to behave the way we know it should work
so as long as i don't know what is the point to have rakutest in sua,
i would be happy to not have it :)

> I do not want to be a tyrant and I don't even want
> to do most of the work on this. Just don't assume I know what I'm
> talking about. I don't.

i really have the same problem with raku so we can probably learn a lot
from each others by maintaining vim-raku.

best regards
marc

**Comment by zostay** [comment]
Okay, then I think `suffixadd` should probably include `.pm6`, `.pm`, and `.rakumod` and maybe `.rakudoc` as I could see someone wanting to look up documentation for a module that way. The `.pm` is useful as some older modules still use that suffix.

However, there is now a new problem, there's a bunch of other changes on this PR. I'd like to keep PR's concise and limited to a single feature/bug/concern so they are easy to approve and discuss.

**Comment by eiro** [comment]
i don't know how to remove some commits of a GH PR so maybe we should close this issue and reopen one?

**Comment by zostay** [comment]
There are a few different ways to strip commits from a branch. If you just need to go back in time, use `git log` to find the last commit you want to keep on a branch and do this:

```
git checkout branch-name
git reset commit-sha
git push -f origin branch-name
```

If you want to keep the commits you made, use `git checkout -b new-branch` right after `git checkout` to create a new branch to preserve them or you can use a combination of `git reflog`, `git log`, and `git cherry-pick` to pull the commits to another branch.

Another option is to rewrite the history of your branch using rebase:

```
git rebase -i branch-name base-ref
```

This will give you an interactive menu for deleting commits, editing commits, and doing all kinds of stuff. This is more than I can explain here, but there are lots of tutorials on interactive git rebase out there you can find online.

**Comment by zostay** [comment]
Or, you can go the route of just closing the PR and starting over if you prefer.

**Pull request closed without merging**
