### PR TITLE
update README

### PR DESCRIPTION
**Pull request by eiro**
* instructions to use vim packages
* update list of supported file extensions

### CODE REVIEW

**Comment by coke** [comment]
Seems fine but has conflicts.

**Comment by eiro** [comment]
in this case, i use git mergetools but i don't know about the github workflow.  may i push a new branch on this issue?

**Comment by eiro** [comment]
hello,

i looked to the conflict. is just rephrase badly what i wrote months ago so you decide what to do about it (i vote for my version to be merged)

**Comment by zostay** [comment]
Rebase and force push the branch to get rid of the conflicts and I will merge.

**Pull request closed without merging**
